#!/bin/sh

LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")

ubus call network.interface.wan status | grep "address" | grep -oE '[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}'
if [ "$?" == "0" ]; then
	echo '['$LOGTIME'] fullconenat No Problem.'
	
else
	echo '['$LOGTIME'] Problem decteted, restarting fullconenat...'
	/etc/init.d/firewall restart
fi
